name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and test
        run: |
          npm i
          npm run build
          npm test

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          token: ${{ secrets.SONAR_TOKEN }}
